# Jykell configuration
markdown: redcarpet
highlighter: pygments
paginate: 5
language: 'en-uk'

# Website info
name: 'Hacklab Mikkeli'
description: "Avoin ja yhteisöllinen työtila tieteestä, teknologiasta ja digitaalisesta taiteesta kiinnostuneille Mikkelissä &bull; An open and community-based workspace for people with interest in science, technology and digital arts in Mikkeli"

# Author's info
author: 'Hacklab Mikkeli'
# edit 'categories' in the front matter of every post to match this username
nickname: Hacklab Mikkeli
bio: 'An open and community-based workspace for people with interest in science, technology and digital arts'
location: 'Mikkeli, FINLAND'
url: 'http://mikkeli.hacklab.fi'
image: 'assets/images/alien_pink.svg'

short_url: 'mikkeli.hacklab.fi'
google_analytics: UA-59054179-1
disqus: username
# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: /
rss_name: feed.xml
# Permalinks
permalink: /:title
# permalink: /author/:username
# permalink: /tag/:tag


# gems and other configs
gems: [jekyll-paginate]
exclude: [vendor]

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...


# Settings for builing master branch with travis-ci
# with jekyll-travis

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
safe: false
lsi: false
username: hacklabmikkeli
repo: hacklabmikkeli.github.io
branch: source
relative_source: ../hacklabmikkeli.github.io/
destination: ../hacklabmikkeli.github.io-pages/
production_url:  https://hacklabmikkeli.github.io/
source_url:      https://github.com/hacklabmikkeli/hacklabmikkeli.github.io/

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
